version: '3.8'

services:
  video-summarizer:
    image: video-summarizer:latest
    ports:
      - "8080:8080"
    
    # Environment variables for runtime configuration
    environment:
      # OpenAI Configuration
      - VS_OPENAI_API_KEY=${OPENAI_API_KEY}
      - VS_OPENAI_MODEL=gpt-4o
      - VS_OPENAI_MAX_TOKENS=10000
      
      # Google Drive Configuration
      - VS_GDRIVE_AUTH_METHOD=oauth
      - VS_GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID}
      - VS_UPLOAD_SUMMARY=true
      - VS_UPLOAD_TRANSCRIPT=true
      
      # Server Configuration
      - VS_SERVER_PORT=8080
      - VS_SERVER_HOST=0.0.0.0
      
      # Paths and Directories
      - VS_ENGINE_CONFIG_PATH=/app/config/config.yaml
      - VS_TMP_DIR=/tmp
      
      # Concurrency Settings
      - VS_CONCURRENCY_TRANSCRIPTION=2
      - VS_CONCURRENCY_SUMMARIZATION=3
      - VS_CONCURRENCY_VIDEO_INFO=1
      - VS_CONCURRENCY_OUTPUT=1
      - VS_CONCURRENCY_CLEANUP=1
      - VS_CONCURRENCY_AUDIO_DOWNLOAD=1
    
    # Volume mounts for configuration and secrets
    volumes:
      # Mount secrets (read-only)
      - ./secrets:/app/secrets:ro
      
      # Mount configuration files (read-only)
      - ./config:/app/config:ro
      
      # Mount logs directory (read-write)
      - ./logs:/app/logs
      
      # Mount temporary directory
      - /tmp:/tmp
    
    # Command to run with correct config paths
    command: ["/app/bin/service", "--service-config", "/app/config/service.yaml"]
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Example .env file content:
# OPENAI_API_KEY=sk-your-openai-api-key-here
# GDRIVE_FOLDER_ID=your-google-drive-folder-id 