level: debug
format: text
file: "test.log"
# Log rotation settings
max_size: 10      # 10 MB before rotation
max_backups: 5    # Keep 5 backup files
max_age: 7        # Keep logs for 7 days
compress: true    # Compress rotated log files 